language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t akhromets/docker-react-travis -f Dockerfile.dev .

# -e CI=true (for exit after tests execution)
script:
  - docker run -e CI=true akhromets/docker-react-travis npm run test -- --coverage
